version: '3.4'
  
services:
  db:
    image: mariadb:latest
    networks:
      trix:
        ipv4_address: 172.26.0.3
    environment:
      MYSQL_ROOT_PASSWORD: trix
      MYSQL_DATABASE: trix
      MYSQL_USER: trix
      MYSQL_PASSWORD: trix
    restart: always
    volumes:
      - db:/var/lib/mysql

  trix:
    image: esterinox/trixcms
    networks:
      trix:
        ipv4_address: 172.26.0.2
    ports:
      - 80:80
    environment: 
      TRIX_APP_LANG: fr 
      TRIX_APP_URL: http://trixcms.example.com

      TRIX_DB_CONNECTION: mysql
      TRIX_DB_HOST: db
      TRIX_DB_PORT: 3306
      TRIX_DB_DATABASE: trix
      TRIX_DB_USERNAME: trix
      TRIX_DB_PASSWORD: trix

      TRIX_MAIL_DRIVER: smtp
      TRIX_MAIL_HOST: mail.example.com
      TRIX_MAIL_PORT: 587
      TRIX_MAIL_USERNAME: admin@trixcms.example.com
      TRIX_MAIL_PASSWORD: xxxx
      TRIX_MAIL_ENCRYPTION: tls
      TRIX_MAIL_FROM_ADDRESS: noreply@trixcms.example.com
      TRIX_MAIL_FROM_NAME: trix

      TRIX_MODULE_PAYMENT: 'true'
      TRIX_MODULE_AUTH: 'true'
    restart: always
    volumes:
      - trix:/var/www/html
      
volumes:
  trix:
  db:

networks:
  trix:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
