version: '3.4'
  
services:
  db:
    image: mariadb:latest
    networks:
      trix:
        ipv4_address: 172.26.0.3
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: trix
      MYSQL_DATABASE: trix
      MYSQL_USER: trix
      MYSQL_PASSWORD: trix
    restart: always
    volumes:
      - db:/var/lib/mysql

  trix:
    image: trix-alpine
    networks:
      trix:
        ipv4_address: 172.26.0.2
    ports:
      - 80:80
    environment: 
      TRIX_ARCH: x86_64
      TRIX_DB_CONNECTION: mysql
      TRIX_DB_HOST: db
      TRIX_DB_PORT: 3306
      TRIX_DB_DATABASE: trix
      TRIX_DB_USERNAME: trix
      TRIX_DB_PASSWORD: trix
    restart: always
    volumes:
      - trix:/var/www/html
      
volumes:
  trix:
  db:

networks:
  trix:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
